# Generated by Django 5.1.4 on 2024-12-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together=set(),
        ),
    ]
